#!/bin/bash

# openstack conf
openstack_cred="${HOME}/novarc"
source $openstack_cred
base_nw_name=${OS_USERNAME}_admin_net
ext_net_name="ext_net"
base_net_id=`neutron net-show $base_nw_name -f table -c id | grep id | awk '{print $4}'`
ext_net_id=`neutron net-show $ext_net_name -f table -c id | grep id | awk '{print $4}'`

# maas instance conf
boot_img_trusty="auto-sync/ubuntu-trusty-14.04-amd64-server-20161020-disk1.img"
boot_img_xenial="auto-sync/ubuntu-xenial-16.04-amd64-server-20161020-disk1.img"
flavor="m1.small"
maas_nw_name="maas-network"
maas_subnw_name="maas-subnet"
maas_rt_name="maas-router"
maas_instance="maas-server"

# pxe boot image conf
pxeboot_img_name="pxeboot.img"
glance_img_name="maas-pxe-image"

# maas conf
ip_range_high="10.12.1.200"
ip_range_low="10.12.1.100"
broadcast_ip="10.12.1.255"
router_ip="10.12.1.1"
static_ip_range_low="10.12.1.201"
static_ip_range_high="10.12.1.250"
maas_server_ip="10.12.1.2"
maas_user_name="admin"
maas_passwd="ubuntu"
dns_forwarder_ip=`less /etc/resolv.conf | grep nameserver | awk '{print $2}'`
