name: moo
version: '1.1'
summary: MAAS On OpenStack
description: |
  A simple tool to deploy a MAAS environment for testing.

grade: stable
confinement: devmode

apps:
  moo:
    command: moo

parts:
  moo:
    plugin: python
    python-version: python3
    source: .
